-- NursePlan Pro: Benutzerprofile, Fachdaten und Datenschutzregeln
-- Diese Datei einmal im Supabase SQL Editor ausführen.

begin;

-- ---------------------------------------------------------------------------
-- 1. Benutzerprofile
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Für jedes neue Auth-Konto automatisch ein Profil anlegen.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
    insert into public.profiles (id, full_name)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', '')
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 2. NursePlan-Pro-Tabellen
-- Jede Zeile besitzt eine owner_id. Sie verbindet die Daten mit dem Konto.
-- ---------------------------------------------------------------------------

create table if not exists public.mitarbeitende (
    id bigint generated by default as identity primary key,
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    name text not null,
    stellenanteil text not null,
    wochenstunden numeric(7,2) not null,
    qualifikation text not null,
    erfahrung text not null,
    nachtdienst text not null,
    monatssollstunden numeric(7,2),
    schutzstatus text not null default 'Keiner',
    feste_dienstart text not null default 'Alle Dienste',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (id, owner_id)
);

create table if not exists public.dienstplaene (
    id bigint generated by default as identity primary key,
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    name text not null,
    startdatum date not null,
    zeitraum integer not null,
    plan_json jsonb not null,
    erstellt_am timestamptz not null default now(),
    aktualisiert_am timestamptz not null default now(),
    unique (id, owner_id)
);

create table if not exists public.einstellungen (
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    schluessel text not null,
    wert_json jsonb not null,
    aktualisiert_am timestamptz not null default now(),
    primary key (owner_id, schluessel)
);

create table if not exists public.vorgaben (
    id bigint generated by default as identity primary key,
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    mitarbeitende_id bigint not null,
    code text not null,
    startdatum date not null,
    enddatum date not null,
    bemerkung text not null default '',
    erstellt_am timestamptz not null default now(),
    unique (id, owner_id),
    constraint vorgaben_gueltiger_zeitraum check (enddatum >= startdatum),
    constraint vorgaben_mitarbeitende_des_kontos
        foreign key (mitarbeitende_id, owner_id)
        references public.mitarbeitende(id, owner_id)
        on delete cascade
);

create table if not exists public.vorlagen (
    id bigint generated by default as identity primary key,
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    name text not null,
    beschreibung text not null default '',
    kategorie text not null default 'Eigene Vorlage',
    daten_json jsonb not null,
    erstellt_am timestamptz not null default now(),
    aktualisiert_am timestamptz not null default now(),
    unique (id, owner_id)
);

create table if not exists public.feedback (
    id bigint generated by default as identity primary key,
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    kategorie text not null,
    bewertung integer not null,
    betreff text not null,
    nachricht text not null,
    kontakt_erlaubt boolean not null default true,
    kontakt_email text not null default '',
    status text not null default 'Neu',
    erstellt_am timestamptz not null default now(),
    constraint feedback_kategorie_gueltig
        check (kategorie in ('Idee', 'Problem', 'Frage', 'Lob')),
    constraint feedback_bewertung_gueltig
        check (bewertung between 1 and 5),
    constraint feedback_betreff_laenge
        check (char_length(betreff) between 3 and 120),
    constraint feedback_nachricht_laenge
        check (char_length(nachricht) between 10 and 3000)
);

create index if not exists idx_mitarbeitende_owner
    on public.mitarbeitende(owner_id);
create index if not exists idx_dienstplaene_owner_aktualisiert
    on public.dienstplaene(owner_id, aktualisiert_am desc);
create index if not exists idx_vorgaben_owner_zeitraum
    on public.vorgaben(owner_id, startdatum, enddatum);
create index if not exists idx_vorlagen_owner_aktualisiert
    on public.vorlagen(owner_id, aktualisiert_am desc);
create index if not exists idx_feedback_owner_erstellt
    on public.feedback(owner_id, erstellt_am desc);

-- Zeitstempel bei Änderungen automatisch aktualisieren.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.set_aktualisiert_am()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.aktualisiert_am = now();
    return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
    before update on public.profiles
    for each row execute procedure public.set_updated_at();

drop trigger if exists mitarbeitende_set_updated_at on public.mitarbeitende;
create trigger mitarbeitende_set_updated_at
    before update on public.mitarbeitende
    for each row execute procedure public.set_updated_at();

drop trigger if exists dienstplaene_set_aktualisiert_am on public.dienstplaene;
create trigger dienstplaene_set_aktualisiert_am
    before update on public.dienstplaene
    for each row execute procedure public.set_aktualisiert_am();

drop trigger if exists einstellungen_set_aktualisiert_am on public.einstellungen;
create trigger einstellungen_set_aktualisiert_am
    before update on public.einstellungen
    for each row execute procedure public.set_aktualisiert_am();

drop trigger if exists vorlagen_set_aktualisiert_am on public.vorlagen;
create trigger vorlagen_set_aktualisiert_am
    before update on public.vorlagen
    for each row execute procedure public.set_aktualisiert_am();

-- ---------------------------------------------------------------------------
-- 3. Rechte und Row Level Security (RLS)
-- Nicht angemeldete Besucher erhalten keinen Zugriff auf Fachdaten.
-- Angemeldete Benutzer dürfen ausschließlich ihre eigenen Zeilen verwenden.
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.mitarbeitende enable row level security;
alter table public.dienstplaene enable row level security;
alter table public.einstellungen enable row level security;
alter table public.vorgaben enable row level security;
alter table public.vorlagen enable row level security;
alter table public.feedback enable row level security;

revoke all on public.profiles from anon;
revoke all on public.mitarbeitende from anon;
revoke all on public.dienstplaene from anon;
revoke all on public.einstellungen from anon;
revoke all on public.vorgaben from anon;
revoke all on public.vorlagen from anon;
revoke all on public.feedback from anon;

grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.mitarbeitende to authenticated;
grant select, insert, update, delete on public.dienstplaene to authenticated;
grant select, insert, update, delete on public.einstellungen to authenticated;
grant select, insert, update, delete on public.vorgaben to authenticated;
grant select, insert, update, delete on public.vorlagen to authenticated;
grant select, insert on public.feedback to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
    on public.profiles for select
    to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own
    on public.profiles for update
    to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = id)
    with check ((select auth.uid()) is not null and (select auth.uid()) = id);

-- Für jede Fachtabelle werden getrennte Richtlinien je Aktion angelegt.
drop policy if exists mitarbeitende_select_own on public.mitarbeitende;
create policy mitarbeitende_select_own on public.mitarbeitende
    for select to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists mitarbeitende_insert_own on public.mitarbeitende;
create policy mitarbeitende_insert_own on public.mitarbeitende
    for insert to authenticated
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists mitarbeitende_update_own on public.mitarbeitende;
create policy mitarbeitende_update_own on public.mitarbeitende
    for update to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists mitarbeitende_delete_own on public.mitarbeitende;
create policy mitarbeitende_delete_own on public.mitarbeitende
    for delete to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists dienstplaene_select_own on public.dienstplaene;
create policy dienstplaene_select_own on public.dienstplaene
    for select to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists dienstplaene_insert_own on public.dienstplaene;
create policy dienstplaene_insert_own on public.dienstplaene
    for insert to authenticated
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists dienstplaene_update_own on public.dienstplaene;
create policy dienstplaene_update_own on public.dienstplaene
    for update to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists dienstplaene_delete_own on public.dienstplaene;
create policy dienstplaene_delete_own on public.dienstplaene
    for delete to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists einstellungen_select_own on public.einstellungen;
create policy einstellungen_select_own on public.einstellungen
    for select to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists einstellungen_insert_own on public.einstellungen;
create policy einstellungen_insert_own on public.einstellungen
    for insert to authenticated
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists einstellungen_update_own on public.einstellungen;
create policy einstellungen_update_own on public.einstellungen
    for update to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists einstellungen_delete_own on public.einstellungen;
create policy einstellungen_delete_own on public.einstellungen
    for delete to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists vorgaben_select_own on public.vorgaben;
create policy vorgaben_select_own on public.vorgaben
    for select to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists vorgaben_insert_own on public.vorgaben;
create policy vorgaben_insert_own on public.vorgaben
    for insert to authenticated
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists vorgaben_update_own on public.vorgaben;
create policy vorgaben_update_own on public.vorgaben
    for update to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists vorgaben_delete_own on public.vorgaben;
create policy vorgaben_delete_own on public.vorgaben
    for delete to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists vorlagen_select_own on public.vorlagen;
create policy vorlagen_select_own on public.vorlagen
    for select to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists vorlagen_insert_own on public.vorlagen;
create policy vorlagen_insert_own on public.vorlagen
    for insert to authenticated
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists vorlagen_update_own on public.vorlagen;
create policy vorlagen_update_own on public.vorlagen
    for update to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id)
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists vorlagen_delete_own on public.vorlagen;
create policy vorlagen_delete_own on public.vorlagen
    for delete to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

drop policy if exists feedback_select_own on public.feedback;
create policy feedback_select_own on public.feedback
    for select to authenticated
    using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
drop policy if exists feedback_insert_own on public.feedback;
create policy feedback_insert_own on public.feedback
    for insert to authenticated
    with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);

commit;
