-- NursePlan Pro: Feedback-Funktion ergänzen
-- Diese Datei einmal im Supabase SQL Editor ausführen.
-- Vorhandene Tabellen und Daten werden nicht gelöscht.

begin;

create table if not exists public.feedback (
    id bigint generated by default as identity primary key,
    owner_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    kategorie text not null,
    bewertung integer not null,
    betreff text not null,
    nachricht text not null,
    kontakt_erlaubt boolean not null default true,
    kontakt_email text not null default '',
    status text not null default 'Neu',
    erstellt_am timestamptz not null default now(),
    constraint feedback_kategorie_gueltig
        check (kategorie in ('Idee', 'Problem', 'Frage', 'Lob')),
    constraint feedback_bewertung_gueltig
        check (bewertung between 1 and 5),
    constraint feedback_betreff_laenge
        check (char_length(betreff) between 3 and 120),
    constraint feedback_nachricht_laenge
        check (char_length(nachricht) between 10 and 3000)
);

create index if not exists idx_feedback_owner_erstellt
    on public.feedback(owner_id, erstellt_am desc);

alter table public.feedback enable row level security;

revoke all on public.feedback from anon;
grant select, insert on public.feedback to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'feedback'
          and policyname = 'feedback_select_own'
    ) then
        create policy feedback_select_own on public.feedback
            for select to authenticated
            using ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'feedback'
          and policyname = 'feedback_insert_own'
    ) then
        create policy feedback_insert_own on public.feedback
            for insert to authenticated
            with check ((select auth.uid()) is not null and (select auth.uid()) = owner_id);
    end if;
end
$$;

commit;
